- name: Create logging namespace
  kubernetes.core.k8s:
    name: logging
    api_version: v1
    kind: Namespace
    state: present

- name: Add Elastic Helm repository
  kubernetes.core.helm_repository:
    name: elastic
    repo_url: https://helm.elastic.co
    state: present

- name: Deploy Elasticsearch
  kubernetes.core.helm:
    name: elasticsearch
    chart_ref: elastic/elasticsearch
    release_namespace: logging
    values:
      replicas: 1
      resources:
        requests:
          memory: "1Gi"
    wait: yes

- name: Deploy Logstash
  kubernetes.core.helm:
    name: logstash
    chart_ref: elastic/logstash
    release_namespace: logging
    values:
      resources:
        requests:
          memory: "512Mi"
    wait: yes

- name: Deploy Kibana
  kubernetes.core.helm:
    name: kibana
    chart_ref: elastic/kibana
    release_namespace: logging
    values:
      resources:
        requests:
          memory: "512Mi"
      service:
        type: NodePort
    wait: yes
