apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: my-app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: your-frontend-image:latest
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://backend-service.my-app-namespace.svc.cluster.local:5000"