apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: my-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: holadmex/3-tier-web-architecture-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://backend-service.my-app-namespace.svc.cluster.local:5000"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m" 
          limit:
            memory: "2Gi"
            cpu: "1"