apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: my-app-namespace 
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - port: 80        
      targetPort: 80   
      nodePort: 30600  
      protocol: TCP
  selector:
    app: frontend




#apiVersion: v1
#kind: Service
#metadata:
  #name: frontend-service
  #namespace: my-app-namespace
  #annotations:
    #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    #service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    #service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:REGION:ACCOUNT_ID:certificate/CERTIFICATE_ID
    #service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
#spec:
  #type: LoadBalancer
  #ports:
    #- port: 80
      #targetPort: 80
      #protocol: TCP
    #- port: 443
      #targetPort: 443
      #protocol: TCP
  #selector:
    #app: app1
