name: ECS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  SONAR_PROJECT_KEY: 3-Tier-web-architecture
  SONAR_ORG: ecs-ci-cd
  AWS_REGION: us-east-1
  ECS_TASK_DEFINITION: task-web-app
  ECS_CLUSTER: Full-stack-web-app
  ECS_SERVICE: web-app-service

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone Repository
        run: |
          git clone https://github.com/holadmex/3-Tier-web-architecture.git

  sonarcloud:
    name: Code Analysis with SonarCloud
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

  docker-build:
    name: Build Frontend Docker Image
    runs-on: ubuntu-latest
    needs: sonarcloud
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          IMAGE_TAG="${{ github.sha[:7] }}"  # Shorten SHA to 7 characters
          docker build -t your-frontend-image:${IMAGE_TAG} -f frontend/Dockerfile frontend/

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv ./bin/trivy /usr/local/bin/
  
      - name: Run Trivy Scan
        run: |
          IMAGE_TAG="${{ github.sha[:7] }}"  # Shorten SHA to 7 characters
          trivy image --severity HIGH,CRITICAL your-frontend-image:${IMAGE_TAG} || exit 1
          
      - name: Push Image to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

      - name: Push Docker Image to ECR
        run: |
          IMAGE_TAG="${{ github.sha[:7] }}"  # Shorten SHA to 7 characters
          docker tag your-frontend-image:${IMAGE_TAG} ${{ secrets.ECR_REPO }}:${IMAGE_TAG}
          docker push ${{ secrets.ECR_REPO }}:${IMAGE_TAG}

      - name: Update ECS Service
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          IMAGE_TAG="${{ github.sha[:7] }}"  # Shorten SHA to 7 characters
          # Fetch current task definition
          ecsTaskDefinition=$(aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }})

          # Update the image in container definitions
          updatedTaskDefinition=$(echo $ecsTaskDefinition | jq -r ".taskDefinition.containerDefinitions | map(if .name == \"frontend\" then .image = \"${{ secrets.ECR_REPO }}:${IMAGE_TAG}\" else . end) | .[]" | jq -s)

          # Register the updated task definition
          newTaskDefinition=$(aws ecs register-task-definition \
            --family ${{ env.ECS_TASK_DEFINITION }} \
            --container-definitions "$updatedTaskDefinition" \
            --requires-compatibilities FARGATE \
            --network-mode awsvpc \
            --cpu 1024 \
            --memory 3072 \
            --execution-role-arn arn:aws:iam::429841094792:role/todo-app-role)

          # Extract revision
          newTaskRevision=$(echo $newTaskDefinition | jq -r '.taskDefinition.revision')

          # Update ECS service
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --task-definition ${{ env.ECS_TASK_DEFINITION }}:$newTaskRevision
