name: ECS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  SONAR_PROJECT_KEY: 3-Tier-web-architecture
  SONAR_ORG: ecs-ci-cd
  AWS_REGION: us-east-1
  ECS_TASK_DEFINITION: web-task
  ECS_CLUSTER: web-app
  ECS_SERVICE: web-service

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone Repository
        run: |
          git clone https://github.com/holadmex/3-Tier-web-architecture.git

  sonarcloud:
    name: Code Analysis with SonarCloud
    runs-on: ubuntu-latest
    needs: build-and-deploy # Run only after build-and-deploy completes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

  docker-build:
    name: Build Frontend Docker Image
    runs-on: ubuntu-latest
    needs: sonarcloud
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t frontend:${GITHUB_SHA::3} -f frontend/Dockerfile frontend/

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv ./bin/trivy /usr/local/bin/
  
      - name: Run Trivy Scan
        run: |
          trivy image --severity HIGH,CRITICAL frontend:${GITHUB_SHA::3} || exit 1
          
      - name: Push Image to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

      - name: Push Docker Image to ECR
        run: |
          docker tag frontend:${GITHUB_SHA::3} ${{ secrets.ECR_REPO }}:${GITHUB_SHA::3}
          docker push ${{ secrets.ECR_REPO }}:${GITHUB_SHA::3}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update ECS Task Definition
        run: |
          # Fetch the current task definition
          aws ecs describe-task-definition \
            --task-definition ${{ env.ECS_TASK_DEFINITION }} \
            > task-definition.json

          # Extract and prepare container definitions
          CONTAINER_DEFINITIONS=$(jq '.taskDefinition.containerDefinitions' task-definition.json)

          # Update image in container definitions
          UPDATED_CONTAINER_DEFINITIONS=$(echo "$CONTAINER_DEFINITIONS" | \
            jq --arg IMAGE "${{ secrets.ECR_REPO }}:${GITHUB_SHA::3}" \
            'map(if .name == "frontend" then .image = $IMAGE else . end)')

          # Register new task definition
          NEW_TASK_DEF=$(aws ecs register-task-definition \
            --family ${{ env.ECS_TASK_DEFINITION }} \
            --container-definitions "$UPDATED_CONTAINER_DEFINITIONS" \
            --requires-compatibilities FARGATE \
            --network-mode awsvpc \
            --cpu 1024 \
            --memory 3072 \
            --execution-role-arn arn:aws:iam::429841094792:role/todo-app-role)

          # Extract the new revision
          NEW_REVISION=$(echo "$NEW_TASK_DEF" | jq -r '.taskDefinition.revision')

          # Update ECS service
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --task-definition ${{ env.ECS_TASK_DEFINITION }}:$NEW_REVISION
            --desired-count = 1

