name: ECS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  SONAR_PROJECT_KEY: 3-Tier-web-architecture
  SONAR_ORG: ecs-ci-cd
  SONAR_SCANNER_VERSION: 5.0.1.3006

jobs:
  sonarcloud:
    name: Code analysis with SonarCloud
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'  # Optional: caches Maven dependencies

      - name: Verify Java Version
        run: java -version

      # Step 2: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for analysis

      # Step 3: Download and Setup SonarScanner CLI with Java Compatibility
      - name: Install SonarScanner CLI
        run: |
          # Download SonarScanner
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION }}-linux.zip
          unzip sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION }}-linux.zip
          
          # Rename and set up path
          mv sonar-scanner-${{ env.SONAR_SCANNER_VERSION }}-linux sonar-scanner
          echo "$PWD/sonar-scanner/bin" >> $GITHUB_PATH

      # Step 4: Run SonarScanner with Enhanced Configuration
      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
          -Dsonar.organization=${{ env.SONAR_ORG }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.sources=. \
          -Dsonar.tests=. \
          -Dsonar.exclusions=**/*.java \
          -X  # Enable debug logging